### ISSUE TITLE
Warning that TIOGA_VERSION is already initialized

### ISSUE THREAD

**Issue by jschwab** [fourmond/tioga#1]
Using the gem for Tioga 1.19 I receive the following warnings:

```
/.../lib/ruby/gems/2.1.0/gems/tioga-1.19/lib/Tioga/FigMkr.rb:52: warning: already initialized constant Tioga::FigureMaker::TIOGA_VERSION
/.../lib/ruby/gems/2.1.0/gems/tioga-1.19/lib/Tioga/FigMkr.rb:46: warning: previous definition of TIOGA_VERSION was here
```

**Comment by wmwolf** [comment]
Hmm... The relevant area is here in FigMkr.rb:

``` ruby
TIOGA_VERSION = if SVN_URL =~ /tags\/tioga\/Tioga%20([^\/]+)/
  $1
else
  "SVN version"
end

TIOGA_VERSION = 1.19
```

Ruby doesn't like it when a constant is redefined, but it does allow it, hence the warnings.

I don't really know what the significance of the SVN business is, so I just commented out the first definition of `TIOGA_VERSION` and left in the hard-coded 1.19, which made the warnings go away.

Any reason that would be bad?

**Comment by fourmond** [comment]
This is my blunder. As we moved away from SVN by moving away from rubyforge, the previous way of finding the version through the SVN tag cannot work anymore. I added the `TIOGA_VERSION = 1.19`, but forgot to remove the previous bit.

Nothing bad, just not very professional-looking
